### ISSUE TITLE
"Resume" playback option does not work

### ISSUE THREAD

**Issue by cconover** [MediaBrowser/Emby.Chromecast#7] opened 2015-10-01 04:04 UTC
When using Chromecast from any device as the controller, the "Resume" playback option does not work. Chromecast will load the video, and initially the playback timer will indicate the position from which the video should resume, but the video actually starts from the beginning. This new playback position then saves to the user profile, and the user loses their place in the video.

I have Emby behind Nginx as a reverse proxy. It works without issue with all other clients except for Chromecast, so the issue does not seem to be with the Nginx configuration.

**Comment by LukePulverenti** [comment] 2015-10-02 00:37
Fixed by https://github.com/MediaBrowser/Emby.Chromecast/commit/ec07f24557dc30735283a4564478cf5ec30b8bdf

Please power cycle your chromecast device and reconnect from the client app.

**Closed by LukePulverenti** 2015-10-02 00:37 UTC

**Comment by cconover** [comment] 2015-10-03 15:46
I did that, on multiple Chromcasts, including the new second generation Chromecast. All of them have the same issue.

**Comment by LukePulverenti** [comment] 2015-10-03 16:34
Then you'll have to see here to supply more info because I can no longer reproduce the problem:

http://emby.media/community/index.php?/topic/739-how-to-report-a-problem/
